### ISSUE TITLE
Sum box can overflow

### ISSUE THREAD

**Issue by chrisvam** [slac-lcls/ami#110]
When users do sums of raw data (e.g. a piranha camera or hsd waveform) the data types are often uint16, which can easily overflow.  It feels like by default we should convert to float32 inside boxes that do summing?  Lingjia in rix reported this issue.

**Comment by syamajala** [comment]
As a more general solution I think we can just do it in this one spot:
https://github.com/slac-lcls/ami/blob/master/ami/graph_nodes.py#L308

Maybe something like:
```
        if self.res is None:
            if isinstance(value, np.ndarray):
                value = value.astype(np.float32)
            self.res = value
        else:
            self.res = np.add(self.res, value)
```

**Comment by syamajala** [comment]
For some reason this does not effect the Accumulator box. I guess if do something like res += np.sum(rest) it promotes it to a larger type.
