### ISSUE TITLE
Displays should send all data from heartbeat at once instead of individual axis

### ISSUE THREAD

**Issue by syamajala** [slac-lcls/ami#30]

**Comment by syamajala** [comment]
/reg/g/pcds/dist/pds/tmo/scripts/MFL/hsd00_live_and_ave_v1.fc

tmoc00118 run 165

**Comment by chrisvam** [comment]
Seshu thinks we don't need this anymore.  We send the heartbeat timestamp with the data.  We check if we received all the data from the same HB before we plot.
