### ISSUE TITLE
Notify users of errors with "managed libraries"

### ISSUE THREAD

**Issue by chrisvam** [slac-lcls/ami#38]
Worked with @valmar and @xianglgithub had inadvertently included these two lines in his .fc file:

  "library": {
    "paths": [
      "/cds/home/x/xiangli/ami/ami_tmo/TMO.py",
      "/cds/group/pcds/dist/pds/tmo/scripts/TMO/TMO.py"
    ]
  },

We think if these had identical function definitions then an error is thrown but the user doesn't see it:  the only symptom is that the plots don't show up.

**Comment by syamajala** [comment]
Just ran into this. I think it should be fixed now. At least it prints something to the console when it happens. I may show a pop-up as well.
