### ISSUE TITLE
Fix AMI Manager Crashes

### ISSUE THREAD

**Issue by chrisvam** [slac-lcls/ami#5]
Ming-Fu says these should be in log files /reg/g/pcds/pds/tmo/logfiles/2020/10/*manager* between 3am and 6am on Oct. 18, although I grep'd for "except" and only found these two (at earlier times):

(ps-3.1.16) tmo-daq:scripts> grep -i except /reg/g/pcds/pds/tmo/logfiles/2020/10/*manager*
/reg/g/pcds/pds/tmo/logfiles/2020/10/17_14:34:14_drp-neh-cmp011:ami-manager.log:During handling of the above exception, another exception occurred:
/reg/g/pcds/pds/tmo/logfiles/2020/10/17_14:34:14_drp-neh-cmp011:ami-manager.log:During handling of the above exception, another exception occurred:
/reg/g/pcds/pds/tmo/logfiles/2020/10/17_23:48:20_drp-neh-cmp011:ami-manager.log:During handling of the above exception, another exception occurred:
/reg/g/pcds/pds/tmo/logfiles/2020/10/17_23:48:20_drp-neh-cmp011:ami-manager.log:During handling of the above exception, another exception occurred:

**Comment by syamajala** [comment]
I only found one bug that caused the manager to crash after looking through the logs. It has been fixed.
