### ISSUE TITLE
Generalize WindowAverage to N-dimensional arrays, if possible

### ISSUE THREAD

**Issue by chrisvam** [slac-lcls/ami#7]

**Comment by syamajala** [comment]
I tried doing this, but found it was too easy to break AMI and end up in inconsistent states. Instead we have different boxes based on the type, there is an AverageWaveform and AverageImage, if we need something like an AverageScalar we add one as well.

**Comment by chrisvam** [comment]
Could we put "window" in the name? Maybe WindowAverage1D, WindowAverage2D, WindowAverageScalar?
