### ISSUE TITLE
Add InfiniteAverage Box

### ISSUE THREAD

**Issue by chrisvam** [slac-lcls/ami#8]
WindowAverage uses Pick-N to average arrays over a time window.  This box would average over all arrays since the beginning of the run (so local worker nodes could keep their own sums and event-counts).

**Comment by syamajala** [comment]
This is done. There is an infinite checkbox for Average0d, Average1d, and Average2d. Depending on whether that box is checked, we will either use an Accumulator or a PickN.

![2020-10-20-151028_3840x2160_scrot](https://user-images.githubusercontent.com/45757/96649692-76369a00-12e6-11eb-9b4e-8cc5f2bc9959.png)
