### ISSUE TITLE
Line width change does not work

### ISSUE THREAD

**Issue by vespos** [slac-lcls/ami#84]
Changing the line-width on any of the plot does not work.

**Comment by vespos** [comment]
Oh ok, interesting! What are the conditions under which we can or not use openGL?

**Comment by syamajala** [comment]
It should work in the hutches I believe. Maybe even with nomachine? You can try it with `--use-opengl` alternatively you can see if the issue is still there if you comment this if out: https://github.com/slac-lcls/ami/blob/master/ami/flowchart/library/Editors.py#L84

**Comment by syamajala** [comment]
This actually works with the latest qt without needing opengl
